# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='level',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
