# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_booking_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='quote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
