# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_auto_20170701_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
