# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20170718_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='level',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
