# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_auto_20170719_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
